--CREATE DATABASE E_COMMERCE;
--E_COMMERCE.ADMIN

-- CREATE TABLE E_COMMERCE.ADMIN.ORDERS
-- (
-- ORDER_ID VARCHAR(1024),
-- CUSTOMER_ID VARCHAR(1024),
-- ORDER_STATUS VARCHAR(10),
-- ORDER_PURCHASE_DATE TIMESTAMP_LTZ,
-- ORDER_APPROVED_DATE TIMESTAMP_LTZ,
-- ORDER_DELIVERED_TO_CARRIER_DATE TIMESTAMP_LTZ,
-- ORDER_DELIVERED_TO_CUSTOMER_DATE TIMESTAMP_LTZ,
-- ORDER_ESTIMATED_DELIVERY_DATE DATE
-- )

-- CREATE STORAGE INTEGRATION ORDER_DATA_INTEGRATION
-- TYPE = EXTERNAL_STAGE
-- STORAGE_PROVIDER = 'S3'
-- ENABLED = TRUE
-- STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::990933658016:role/Snowflake_s3_bucket_access'
-- STORAGE_ALLOWED_LOCATIONS = ('s3://amzn-s3-firstproject-bucket/Orders/')

-- desc integration ORDER_DATA_INTEGRATION;

-- CREATE FILE FORMAT ORDER_FILES
-- TYPE = 'csv'
-- FIELD_DELIMITER = ','
-- SKIP_HEADER = 1


-- create stage order_stage
-- url = 's3://amzn-s3-firstproject-bucket/Orders/'
-- STORAGE_INTEGRATION = "ORDER_DATA_INTEGRATION"
-- FILE_FORMAT = "ORDER_FILES"

-- COPY INTO ORDERS
-- FROM @order_stage
-- ON_ERROR = 'CONTINUE'

-- ALTER TABLE ORDERS 
-- ALTER COLUMN ORDER_STATUS SET DATA TYPE VARCHAR(20)

-- ALTER TABLE ORDERS
-- RENAME TO RAW_ORDERS;

-- DELETE FROM RAW_ORDERS

-- CREATE OR REPLACE PIPE orders_pipe
--   AUTO_INGEST = TRUE
-- AS
-- COPY INTO ORDERS
-- FROM @order_stage
-- ON_ERROR = 'CONTINUE';

-- CREATE OR REPLACE PIPE orders_pipe
--   AUTO_INGEST = TRUE
-- AS
-- COPY INTO RAW_ORDERS (
--   ORDER_ID ,
-- CUSTOMER_ID ,
-- ORDER_STATUS ,
-- ORDER_PURCHASE_DATE ,
-- ORDER_APPROVED_DATE ,
-- ORDER_DELIVERED_TO_CARRIER_DATE ,
-- ORDER_DELIVERED_TO_CUSTOMER_DATE ,
-- ORDER_ESTIMATED_DELIVERY_DATE
-- )
-- FROM (
--   SELECT
--     $1,
--     $2,
--     $3,
--     $4,
--     $5,
--     $6,
--     $7,
--     $8
--   FROM @order_stage
-- )
-- ON_ERROR = 'CONTINUE';

-- desc pipe orders_pipe


-- select * from RAW_ORDERS where order_status like 'pending%'

-- SELECT SYSTEM$PIPE_STATUS('orders_pipe');

SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_ORDERS',
    START_TIME => DATEADD(hour, -1, CURRENT_TIMESTAMP())
  )
);

-- LIST @order_stage;


-- DROP PIPE orders_pipe;

--Creating Task and streams on the raw tables to capture Changed data (CDC)

-- CREATE TABLE STAGE_ORDERS
-- (
-- ORDER_ID VARCHAR(1024),
-- CUSTOMER_ID VARCHAR(1024),
-- ORDER_STATUS VARCHAR(20),
-- ORDER_PURCHASE_DATE TIMESTAMP_LTZ,
-- ORDER_APPROVED_DATE TIMESTAMP_LTZ,
-- ORDER_DELIVERED_TO_CARRIER_DATE TIMESTAMP_LTZ,
-- ORDER_DELIVERED_TO_CUSTOMER_DATE TIMESTAMP_LTZ,
-- ORDER_ESTIMATED_DELIVERY_DATE DATE
-- )


CREATE OR REPLACE STREAM CDC_ORDERS_STREAM 
ON TABLE RAW_ORDERS;


DROP STREAM CDC_ORDERS

SELECT * FROM CDC_ORDERS_STREAM ;

CREATE OR REPLACE TASK cdc_orders_task
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CDC_ORDERS_STREAM')
AS
MERGE INTO STAGE_ORDERS SO
USING(
SELECT 
ORDER_ID ,
CUSTOMER_ID ,
ORDER_STATUS ,
ORDER_PURCHASE_DATE ,
ORDER_APPROVED_DATE ,
ORDER_DELIVERED_TO_CARRIER_DATE ,
ORDER_DELIVERED_TO_CUSTOMER_DATE ,
ORDER_ESTIMATED_DELIVERY_DATE
FROM CDC_ORDERS_STREAM
WHERE METADATA$ACTION = 'INSERT'
)SRC
ON SO.ORDER_ID = SRC.ORDER_ID
WHEN MATCHED THEN
UPDATE SET
SO.ORDER_ID =	SRC.ORDER_ID ,
SO.CUSTOMER_ID =	SRC.CUSTOMER_ID ,
SO.ORDER_STATUS =	SRC.ORDER_STATUS ,
SO.ORDER_PURCHASE_DATE =	SRC.ORDER_PURCHASE_DATE ,
SO.ORDER_APPROVED_DATE =	SRC.ORDER_APPROVED_DATE ,
SO.ORDER_DELIVERED_TO_CARRIER_DATE =	SRC.ORDER_DELIVERED_TO_CARRIER_DATE ,
SO.ORDER_DELIVERED_TO_CUSTOMER_DATE = 	SRC.ORDER_DELIVERED_TO_CUSTOMER_DATE ,
SO.ORDER_ESTIMATED_DELIVERY_DATE = 	SRC.ORDER_ESTIMATED_DELIVERY_DATE

WHEN NOT MATCHED THEN
INSERT(
ORDER_ID ,
CUSTOMER_ID ,
ORDER_STATUS ,
ORDER_PURCHASE_DATE ,
ORDER_APPROVED_DATE ,
ORDER_DELIVERED_TO_CARRIER_DATE ,
ORDER_DELIVERED_TO_CUSTOMER_DATE ,
ORDER_ESTIMATED_DELIVERY_DATE
) 
VALUES(
SRC.ORDER_ID ,
SRC.CUSTOMER_ID ,
SRC.ORDER_STATUS ,
SRC.ORDER_PURCHASE_DATE ,
SRC.ORDER_APPROVED_DATE ,
SRC.ORDER_DELIVERED_TO_CARRIER_DATE ,
SRC.ORDER_DELIVERED_TO_CUSTOMER_DATE ,
SRC.ORDER_ESTIMATED_DELIVERY_DATE
)

select * from STAGE_ORDERS

SHOW TASKS LIKE 'CDC_ORDERS_TASK';
ALTER TASK cdc_orders_task RESUME;

